// Built-in food database: name, typical serving, calories per serving.
// Add your own foods at the bottom — same format.
const FOOD_DB = [
  // Breakfast
  { name: "Egg (large, boiled/fried)", serving: "1 egg", kcal: 78 },
  { name: "Scrambled eggs", serving: "2 eggs", kcal: 180 },
  { name: "Omelette (cheese)", serving: "2-egg omelette", kcal: 290 },
  { name: "Bacon", serving: "2 strips", kcal: 90 },
  { name: "Sausage link", serving: "1 link", kcal: 100 },
  { name: "Pancake", serving: "1 medium (no syrup)", kcal: 90 },
  { name: "Maple syrup", serving: "2 tbsp", kcal: 100 },
  { name: "Waffle", serving: "1 round waffle", kcal: 220 },
  { name: "French toast", serving: "1 slice", kcal: 150 },
  { name: "Oatmeal (cooked)", serving: "1 cup", kcal: 160 },
  { name: "Cereal (corn flakes)", serving: "1 cup", kcal: 100 },
  { name: "Cereal (granola)", serving: "1/2 cup", kcal: 220 },
  { name: "Toast (white bread)", serving: "1 slice", kcal: 75 },
  { name: "Toast (whole wheat)", serving: "1 slice", kcal: 80 },
  { name: "Bagel (plain)", serving: "1 bagel", kcal: 280 },
  { name: "Croissant", serving: "1 medium", kcal: 230 },
  { name: "Muffin (blueberry)", serving: "1 medium", kcal: 380 },
  { name: "Donut (glazed)", serving: "1 donut", kcal: 260 },
  { name: "Yogurt (plain)", serving: "1 cup", kcal: 150 },
  { name: "Greek yogurt (plain, nonfat)", serving: "1 cup", kcal: 130 },
  { name: "Cottage cheese", serving: "1/2 cup", kcal: 110 },

  // Fruits
  { name: "Apple", serving: "1 medium", kcal: 95 },
  { name: "Banana", serving: "1 medium", kcal: 105 },
  { name: "Orange", serving: "1 medium", kcal: 62 },
  { name: "Grapes", serving: "1 cup", kcal: 62 },
  { name: "Strawberries", serving: "1 cup", kcal: 49 },
  { name: "Blueberries", serving: "1 cup", kcal: 84 },
  { name: "Watermelon", serving: "1 cup diced", kcal: 46 },
  { name: "Pineapple", serving: "1 cup chunks", kcal: 82 },
  { name: "Mango", serving: "1 cup sliced", kcal: 99 },
  { name: "Avocado", serving: "1/2 avocado", kcal: 120 },
  { name: "Peach", serving: "1 medium", kcal: 59 },
  { name: "Pear", serving: "1 medium", kcal: 101 },

  // Vegetables & sides
  { name: "Broccoli (cooked)", serving: "1 cup", kcal: 55 },
  { name: "Carrots (raw)", serving: "1 medium", kcal: 25 },
  { name: "Spinach (raw)", serving: "2 cups", kcal: 14 },
  { name: "Salad (garden, no dressing)", serving: "1 bowl", kcal: 35 },
  { name: "Caesar salad (with dressing)", serving: "1 bowl", kcal: 360 },
  { name: "Ranch dressing", serving: "2 tbsp", kcal: 130 },
  { name: "Corn (cooked)", serving: "1 ear", kcal: 90 },
  { name: "Green beans (cooked)", serving: "1 cup", kcal: 44 },
  { name: "Baked potato", serving: "1 medium", kcal: 160 },
  { name: "Mashed potatoes", serving: "1 cup", kcal: 240 },
  { name: "Sweet potato (baked)", serving: "1 medium", kcal: 100 },
  { name: "French fries", serving: "medium serving", kcal: 365 },
  { name: "Onion rings", serving: "8-9 rings", kcal: 280 },
  { name: "Coleslaw", serving: "1/2 cup", kcal: 150 },

  // Grains & pasta
  { name: "White rice (cooked)", serving: "1 cup", kcal: 205 },
  { name: "Brown rice (cooked)", serving: "1 cup", kcal: 215 },
  { name: "Fried rice", serving: "1 cup", kcal: 240 },
  { name: "Pasta with marinara", serving: "1.5 cups", kcal: 380 },
  { name: "Spaghetti with meatballs", serving: "1.5 cups", kcal: 550 },
  { name: "Mac and cheese", serving: "1 cup", kcal: 350 },
  { name: "Ramen (instant, prepared)", serving: "1 package", kcal: 380 },
  { name: "Quinoa (cooked)", serving: "1 cup", kcal: 222 },
  { name: "Tortilla (flour, 8\")", serving: "1 tortilla", kcal: 140 },
  { name: "Bread roll", serving: "1 roll", kcal: 110 },

  // Protein mains
  { name: "Chicken breast (grilled)", serving: "1 breast (6 oz)", kcal: 280 },
  { name: "Chicken thigh (roasted)", serving: "1 thigh", kcal: 210 },
  { name: "Fried chicken", serving: "1 breast piece", kcal: 360 },
  { name: "Chicken nuggets", serving: "6 nuggets", kcal: 280 },
  { name: "Chicken wings", serving: "6 wings", kcal: 430 },
  { name: "Steak (sirloin)", serving: "6 oz", kcal: 340 },
  { name: "Ground beef (cooked, 85%)", serving: "4 oz", kcal: 240 },
  { name: "Pork chop (grilled)", serving: "1 chop (6 oz)", kcal: 290 },
  { name: "Ham (sliced)", serving: "3 oz", kcal: 120 },
  { name: "Salmon (baked)", serving: "6 oz fillet", kcal: 350 },
  { name: "Tilapia (baked)", serving: "6 oz fillet", kcal: 220 },
  { name: "Tuna (canned in water)", serving: "1 can", kcal: 120 },
  { name: "Shrimp (cooked)", serving: "3 oz", kcal: 85 },
  { name: "Tofu (firm)", serving: "1/2 cup", kcal: 95 },
  { name: "Turkey breast (sliced)", serving: "3 oz", kcal: 90 },

  // Fast food & meals
  { name: "Hamburger", serving: "1 burger", kcal: 350 },
  { name: "Cheeseburger", serving: "1 burger", kcal: 450 },
  { name: "Double cheeseburger", serving: "1 burger", kcal: 650 },
  { name: "Hot dog (with bun)", serving: "1 hot dog", kcal: 290 },
  { name: "Pizza (cheese)", serving: "1 slice", kcal: 285 },
  { name: "Pizza (pepperoni)", serving: "1 slice", kcal: 310 },
  { name: "Taco (beef, hard shell)", serving: "1 taco", kcal: 210 },
  { name: "Burrito (chicken)", serving: "1 burrito", kcal: 650 },
  { name: "Burrito bowl (chicken)", serving: "1 bowl", kcal: 700 },
  { name: "Quesadilla (cheese)", serving: "1 quesadilla", kcal: 500 },
  { name: "Chicken sandwich (fried)", serving: "1 sandwich", kcal: 530 },
  { name: "Grilled cheese sandwich", serving: "1 sandwich", kcal: 400 },
  { name: "BLT sandwich", serving: "1 sandwich", kcal: 420 },
  { name: "Turkey sandwich", serving: "1 sandwich", kcal: 330 },
  { name: "PB&J sandwich", serving: "1 sandwich", kcal: 380 },
  { name: "Sub sandwich (6\", turkey)", serving: "6 inch sub", kcal: 280 },
  { name: "Sushi roll (California)", serving: "8 pieces", kcal: 300 },
  { name: "Chicken noodle soup", serving: "1 cup", kcal: 90 },
  { name: "Chili (with beans)", serving: "1 cup", kcal: 290 },
  { name: "Lasagna", serving: "1 piece", kcal: 380 },
  { name: "Chicken curry with rice", serving: "1 plate", kcal: 580 },
  { name: "Pad thai (chicken)", serving: "1 plate", kcal: 650 },
  { name: "General Tso's chicken with rice", serving: "1 plate", kcal: 800 },

  // Snacks
  { name: "Potato chips", serving: "1 oz (~15 chips)", kcal: 150 },
  { name: "Tortilla chips", serving: "1 oz (~10 chips)", kcal: 140 },
  { name: "Salsa", serving: "2 tbsp", kcal: 10 },
  { name: "Guacamole", serving: "2 tbsp", kcal: 50 },
  { name: "Popcorn (buttered)", serving: "2 cups", kcal: 110 },
  { name: "Pretzels", serving: "1 oz", kcal: 110 },
  { name: "Peanuts", serving: "1 oz (~28 nuts)", kcal: 160 },
  { name: "Almonds", serving: "1 oz (~23 nuts)", kcal: 165 },
  { name: "Cashews", serving: "1 oz", kcal: 160 },
  { name: "Peanut butter", serving: "2 tbsp", kcal: 190 },
  { name: "Trail mix", serving: "1/4 cup", kcal: 170 },
  { name: "Protein bar", serving: "1 bar", kcal: 200 },
  { name: "Granola bar", serving: "1 bar", kcal: 120 },
  { name: "Cheese (cheddar)", serving: "1 oz slice", kcal: 115 },
  { name: "String cheese", serving: "1 stick", kcal: 80 },
  { name: "Crackers (saltine)", serving: "5 crackers", kcal: 65 },
  { name: "Beef jerky", serving: "1 oz", kcal: 80 },
  { name: "Hummus", serving: "2 tbsp", kcal: 70 },

  // Sweets & desserts
  { name: "Chocolate chip cookie", serving: "1 medium", kcal: 80 },
  { name: "Brownie", serving: "1 square", kcal: 230 },
  { name: "Ice cream (vanilla)", serving: "1/2 cup", kcal: 140 },
  { name: "Ice cream (chocolate)", serving: "1/2 cup", kcal: 145 },
  { name: "Milkshake", serving: "16 oz", kcal: 580 },
  { name: "Chocolate bar (milk)", serving: "1.5 oz bar", kcal: 230 },
  { name: "Candy (gummy bears)", serving: "~17 pieces", kcal: 140 },
  { name: "Cake (chocolate, frosted)", serving: "1 slice", kcal: 350 },
  { name: "Cheesecake", serving: "1 slice", kcal: 400 },
  { name: "Apple pie", serving: "1 slice", kcal: 300 },
  { name: "Cupcake (frosted)", serving: "1 cupcake", kcal: 250 },

  // Drinks
  { name: "Coffee (black)", serving: "1 cup", kcal: 2 },
  { name: "Coffee with cream & sugar", serving: "1 cup", kcal: 60 },
  { name: "Latte (whole milk)", serving: "16 oz", kcal: 190 },
  { name: "Caramel frappuccino", serving: "16 oz", kcal: 380 },
  { name: "Tea (unsweetened)", serving: "1 cup", kcal: 2 },
  { name: "Sweet tea", serving: "16 oz", kcal: 180 },
  { name: "Orange juice", serving: "8 oz", kcal: 110 },
  { name: "Apple juice", serving: "8 oz", kcal: 115 },
  { name: "Milk (whole)", serving: "1 cup", kcal: 150 },
  { name: "Milk (2%)", serving: "1 cup", kcal: 120 },
  { name: "Milk (skim)", serving: "1 cup", kcal: 80 },
  { name: "Chocolate milk", serving: "1 cup", kcal: 210 },
  { name: "Soda (cola)", serving: "12 oz can", kcal: 140 },
  { name: "Diet soda", serving: "12 oz can", kcal: 0 },
  { name: "Energy drink", serving: "16 oz can", kcal: 210 },
  { name: "Sports drink", serving: "20 oz", kcal: 130 },
  { name: "Beer (regular)", serving: "12 oz", kcal: 150 },
  { name: "Beer (light)", serving: "12 oz", kcal: 100 },
  { name: "Wine (red)", serving: "5 oz glass", kcal: 125 },
  { name: "Smoothie (fruit)", serving: "16 oz", kcal: 280 },
  { name: "Protein shake", serving: "1 scoop + water", kcal: 130 },
];
