// Built-in food database: name, typical serving, calories per serving.
// Add your own foods at the bottom — same format.
const FOOD_DB = [
  // Breakfast
  { name: "Egg (large, boiled/fried)", serving: "1 egg", kcal: 78 },
  { name: "Scrambled eggs", serving: "2 eggs", kcal: 180 },
  { name: "Omelette (cheese)", serving: "2-egg omelette", kcal: 290 },
  { name: "Bacon", serving: "2 strips", kcal: 90 },
  { name: "Sausage link", serving: "1 link", kcal: 100 },
  { name: "Pancake", serving: "1 medium (no syrup)", kcal: 90 },
  { name: "Maple syrup", serving: "2 tbsp", kcal: 100 },
  { name: "Waffle", serving: "1 round waffle", kcal: 220 },
  { name: "French toast", serving: "1 slice", kcal: 150 },
  { name: "Oatmeal (cooked)", serving: "1 cup", kcal: 160 },
  { name: "Cereal (corn flakes)", serving: "1 cup", kcal: 100 },
  { name: "Cereal (granola)", serving: "1/2 cup", kcal: 220 },
  { name: "Toast (white bread)", serving: "1 slice", kcal: 75 },
  { name: "Toast (whole wheat)", serving: "1 slice", kcal: 80 },
  { name: "Bagel (plain)", serving: "1 bagel", kcal: 280 },
  { name: "Croissant", serving: "1 medium", kcal: 230 },
  { name: "Muffin (blueberry)", serving: "1 medium", kcal: 380 },
  { name: "Donut (glazed)", serving: "1 donut", kcal: 260 },
  { name: "Yogurt (plain)", serving: "1 cup", kcal: 150 },
  { name: "Greek yogurt (plain, nonfat)", serving: "1 cup", kcal: 130 },
  { name: "Cottage cheese", serving: "1/2 cup", kcal: 110 },

  // Fruits
  { name: "Apple", serving: "1 medium", kcal: 95 },
  { name: "Banana", serving: "1 medium", kcal: 105 },
  { name: "Orange", serving: "1 medium", kcal: 62 },
  { name: "Grapes", serving: "1 cup", kcal: 62 },
  { name: "Strawberries", serving: "1 cup", kcal: 49 },
  { name: "Blueberries", serving: "1 cup", kcal: 84 },
  { name: "Watermelon", serving: "1 cup diced", kcal: 46 },
  { name: "Pineapple", serving: "1 cup chunks", kcal: 82 },
  { name: "Mango", serving: "1 cup sliced", kcal: 99 },
  { name: "Avocado", serving: "1/2 avocado", kcal: 120 },
  { name: "Peach", serving: "1 medium", kcal: 59 },
  { name: "Pear", serving: "1 medium", kcal: 101 },

  // Vegetables & sides
  { name: "Broccoli (cooked)", serving: "1 cup", kcal: 55 },
  { name: "Carrots (raw)", serving: "1 medium", kcal: 25 },
  { name: "Spinach (raw)", serving: "2 cups", kcal: 14 },
  { name: "Salad (garden, no dressing)", serving: "1 bowl", kcal: 35 },
  { name: "Caesar salad (with dressing)", serving: "1 bowl", kcal: 360 },
  { name: "Ranch dressing", serving: "2 tbsp", kcal: 130 },
  { name: "Corn (cooked)", serving: "1 ear", kcal: 90 },
  { name: "Green beans (cooked)", serving: "1 cup", kcal: 44 },
  { name: "Baked potato", serving: "1 medium", kcal: 160 },
  { name: "Mashed potatoes", serving: "1 cup", kcal: 240 },
  { name: "Sweet potato (baked)", serving: "1 medium", kcal: 100 },
  { name: "French fries", serving: "medium serving", kcal: 365 },
  { name: "Onion rings", serving: "8-9 rings", kcal: 280 },
  { name: "Coleslaw", serving: "1/2 cup", kcal: 150 },

  // Grains & pasta
  { name: "White rice (cooked)", serving: "1 cup", kcal: 205 },
  { name: "Brown rice (cooked)", serving: "1 cup", kcal: 215 },
  { name: "Fried rice", serving: "1 cup", kcal: 240 },
  { name: "Pasta with marinara", serving: "1.5 cups", kcal: 380 },
  { name: "Spaghetti with meatballs", serving: "1.5 cups", kcal: 550 },
  { name: "Mac and cheese", serving: "1 cup", kcal: 350 },
  { name: "Ramen (instant, prepared)", serving: "1 package", kcal: 380 },
  { name: "Quinoa (cooked)", serving: "1 cup", kcal: 222 },
  { name: "Tortilla (flour, 8\")", serving: "1 tortilla", kcal: 140 },
  { name: "Bread roll", serving: "1 roll", kcal: 110 },

  // Protein mains
  { name: "Chicken breast (grilled)", serving: "1 breast (6 oz)", kcal: 280 },
  { name: "Chicken thigh (roasted)", serving: "1 thigh", kcal: 210 },
  { name: "Fried chicken", serving: "1 breast piece", kcal: 360 },
  { name: "Chicken nuggets", serving: "6 nuggets", kcal: 280 },
  { name: "Chicken wings", serving: "6 wings", kcal: 430 },
  { name: "Steak (sirloin)", serving: "6 oz", kcal: 340 },
  { name: "Ground beef (cooked, 85%)", serving: "4 oz", kcal: 240 },
  { name: "Pork chop (grilled)", serving: "1 chop (6 oz)", kcal: 290 },
  { name: "Ham (sliced)", serving: "3 oz", kcal: 120 },
  { name: "Salmon (baked)", serving: "6 oz fillet", kcal: 350 },
  { name: "Tilapia (baked)", serving: "6 oz fillet", kcal: 220 },
  { name: "Tuna (canned in water)", serving: "1 can", kcal: 120 },
  { name: "Shrimp (cooked)", serving: "3 oz", kcal: 85 },
  { name: "Tofu (firm)", serving: "1/2 cup", kcal: 95 },
  { name: "Turkey breast (sliced)", serving: "3 oz", kcal: 90 },

  // Fast food & meals
  { name: "Hamburger", serving: "1 burger", kcal: 350 },
  { name: "Cheeseburger", serving: "1 burger", kcal: 450 },
  { name: "Double cheeseburger", serving: "1 burger", kcal: 650 },
  { name: "Hot dog (with bun)", serving: "1 hot dog", kcal: 290 },
  { name: "Pizza (cheese)", serving: "1 slice", kcal: 285 },
  { name: "Pizza (pepperoni)", serving: "1 slice", kcal: 310 },
  { name: "Taco (beef, hard shell)", serving: "1 taco", kcal: 210 },
  { name: "Burrito (chicken)", serving: "1 burrito", kcal: 650 },
  { name: "Burrito bowl (chicken)", serving: "1 bowl", kcal: 700 },
  { name: "Quesadilla (cheese)", serving: "1 quesadilla", kcal: 500 },
  { name: "Chicken sandwich (fried)", serving: "1 sandwich", kcal: 530 },
  { name: "Grilled cheese sandwich", serving: "1 sandwich", kcal: 400 },
  { name: "BLT sandwich", serving: "1 sandwich", kcal: 420 },
  { name: "Turkey sandwich", serving: "1 sandwich", kcal: 330 },
  { name: "PB&J sandwich", serving: "1 sandwich", kcal: 380 },
  { name: "Sub sandwich (6\", turkey)", serving: "6 inch sub", kcal: 280 },
  { name: "Sushi roll (California)", serving: "8 pieces", kcal: 300 },
  { name: "Chicken noodle soup", serving: "1 cup", kcal: 90 },
  { name: "Chili (with beans)", serving: "1 cup", kcal: 290 },
  { name: "Lasagna", serving: "1 piece", kcal: 380 },
  { name: "Chicken curry with rice", serving: "1 plate", kcal: 580 },
  { name: "Pad thai (chicken)", serving: "1 plate", kcal: 650 },
  { name: "General Tso's chicken with rice", serving: "1 plate", kcal: 800 },

  // Snacks
  { name: "Potato chips", serving: "1 oz (~15 chips)", kcal: 150 },
  { name: "Tortilla chips", serving: "1 oz (~10 chips)", kcal: 140 },
  { name: "Salsa", serving: "2 tbsp", kcal: 10 },
  { name: "Guacamole", serving: "2 tbsp", kcal: 50 },
  { name: "Popcorn (buttered)", serving: "2 cups", kcal: 110 },
  { name: "Pretzels", serving: "1 oz", kcal: 110 },
  { name: "Peanuts", serving: "1 oz (~28 nuts)", kcal: 160 },
  { name: "Almonds", serving: "1 oz (~23 nuts)", kcal: 165 },
  { name: "Cashews", serving: "1 oz", kcal: 160 },
  { name: "Peanut butter", serving: "2 tbsp", kcal: 190 },
  { name: "Trail mix", serving: "1/4 cup", kcal: 170 },
  { name: "Protein bar", serving: "1 bar", kcal: 200 },
  { name: "Granola bar", serving: "1 bar", kcal: 120 },
  { name: "Cheese (cheddar)", serving: "1 oz slice", kcal: 115 },
  { name: "String cheese", serving: "1 stick", kcal: 80 },
  { name: "Crackers (saltine)", serving: "5 crackers", kcal: 65 },
  { name: "Beef jerky", serving: "1 oz", kcal: 80 },
  { name: "Hummus", serving: "2 tbsp", kcal: 70 },

  // Sweets & desserts
  { name: "Chocolate chip cookie", serving: "1 medium", kcal: 80 },
  { name: "Brownie", serving: "1 square", kcal: 230 },
  { name: "Ice cream (vanilla)", serving: "1/2 cup", kcal: 140 },
  { name: "Ice cream (chocolate)", serving: "1/2 cup", kcal: 145 },
  { name: "Milkshake", serving: "16 oz", kcal: 580 },
  { name: "Chocolate bar (milk)", serving: "1.5 oz bar", kcal: 230 },
  { name: "Candy (gummy bears)", serving: "~17 pieces", kcal: 140 },
  { name: "Cake (chocolate, frosted)", serving: "1 slice", kcal: 350 },
  { name: "Cheesecake", serving: "1 slice", kcal: 400 },
  { name: "Apple pie", serving: "1 slice", kcal: 300 },
  { name: "Cupcake (frosted)", serving: "1 cupcake", kcal: 250 },

  // Drinks
  { name: "Coffee (black)", serving: "1 cup", kcal: 2 },
  { name: "Coffee with cream & sugar", serving: "1 cup", kcal: 60 },
  { name: "Latte (whole milk)", serving: "16 oz", kcal: 190 },
  { name: "Caramel frappuccino", serving: "16 oz", kcal: 380 },
  { name: "Tea (unsweetened)", serving: "1 cup", kcal: 2 },
  { name: "Sweet tea", serving: "16 oz", kcal: 180 },
  { name: "Orange juice", serving: "8 oz", kcal: 110 },
  { name: "Apple juice", serving: "8 oz", kcal: 115 },
  { name: "Milk (whole)", serving: "1 cup", kcal: 150 },
  { name: "Milk (2%)", serving: "1 cup", kcal: 120 },
  { name: "Milk (skim)", serving: "1 cup", kcal: 80 },
  { name: "Chocolate milk", serving: "1 cup", kcal: 210 },
  { name: "Soda (cola)", serving: "12 oz can", kcal: 140 },
  { name: "Diet soda", serving: "12 oz can", kcal: 0 },
  { name: "Energy drink", serving: "16 oz can", kcal: 210 },
  { name: "Sports drink", serving: "20 oz", kcal: 130 },
  { name: "Beer (regular)", serving: "12 oz", kcal: 150 },
  { name: "Beer (light)", serving: "12 oz", kcal: 100 },
  { name: "Wine (red)", serving: "5 oz glass", kcal: 125 },
  { name: "Smoothie (fruit)", serving: "16 oz", kcal: 280 },
  { name: "Protein shake", serving: "1 scoop + water", kcal: 130 },

  // Fast food chains (published values, approximate)
  { name: "McDonald's Big Mac", serving: "1 burger", kcal: 590 },
  { name: "McDonald's Quarter Pounder w/ Cheese", serving: "1 burger", kcal: 520 },
  { name: "McDonald's McChicken", serving: "1 sandwich", kcal: 400 },
  { name: "McDonald's fries", serving: "medium", kcal: 320 },
  { name: "McDonald's McNuggets", serving: "10 piece", kcal: 410 },
  { name: "Burger King Whopper", serving: "1 burger", kcal: 670 },
  { name: "Wendy's Dave's Single", serving: "1 burger", kcal: 590 },
  { name: "Wendy's Baconator", serving: "1 burger", kcal: 950 },
  { name: "Chick-fil-A Chicken Sandwich", serving: "1 sandwich", kcal: 440 },
  { name: "Chick-fil-A Nuggets", serving: "12 count", kcal: 380 },
  { name: "Chick-fil-A Waffle Fries", serving: "medium", kcal: 420 },
  { name: "Popeyes Chicken Sandwich", serving: "1 sandwich", kcal: 700 },
  { name: "Taco Bell Crunchwrap Supreme", serving: "1 crunchwrap", kcal: 530 },
  { name: "Taco Bell Doritos Locos Taco", serving: "1 taco", kcal: 170 },
  { name: "Taco Bell Bean Burrito", serving: "1 burrito", kcal: 350 },
  { name: "In-N-Out Double-Double", serving: "1 burger", kcal: 670 },
  { name: "In-N-Out fries", serving: "1 order", kcal: 370 },
  { name: "Five Guys Cheeseburger", serving: "1 burger", kcal: 840 },
  { name: "Five Guys fries", serving: "little", kcal: 530 },
  { name: "Raising Cane's chicken finger", serving: "1 finger", kcal: 130 },
  { name: "Raising Cane's crinkle fries", serving: "1 order", kcal: 390 },
  { name: "Raising Cane's Texas toast", serving: "1 slice", kcal: 150 },
  { name: "Raising Cane's sauce", serving: "1 cup", kcal: 190 },
  { name: "Panda Express Orange Chicken", serving: "1 serving", kcal: 490 },
  { name: "Panda Express Chow Mein", serving: "1 serving", kcal: 510 },
  { name: "Panda Express Fried Rice", serving: "1 serving", kcal: 520 },
  { name: "Domino's pepperoni pizza", serving: "1 slice (large)", kcal: 290 },
  { name: "KFC fried chicken breast", serving: "1 piece", kcal: 390 },
  { name: "Chipotle chips", serving: "1 bag", kcal: 540 },
];

// "Eating out" meal builder: pick a base, check what's in it, calories sum up.
// Values from the chains' published nutrition info (approximate).
const MEAL_BUILDER = {
  "Chipotle": {
    formats: [
      { name: "Bowl / Salad", kcal: 0, mult: 1 },
      { name: "Burrito (flour tortilla)", kcal: 320, mult: 1 },
      { name: "3 Tacos (shells)", kcal: 240, mult: 1 },
    ],
    groups: [
      { name: "Protein", items: [
        { name: "Chicken", kcal: 180 }, { name: "Steak", kcal: 150 },
        { name: "Barbacoa", kcal: 170 }, { name: "Carnitas", kcal: 210 },
        { name: "Sofritas", kcal: 150 }, { name: "Double protein (add again)", kcal: 180 },
      ]},
      { name: "Rice & Beans", items: [
        { name: "White rice", kcal: 210 }, { name: "Brown rice", kcal: 210 },
        { name: "Black beans", kcal: 130 }, { name: "Pinto beans", kcal: 130 },
      ]},
      { name: "Toppings", items: [
        { name: "Fajita veggies", kcal: 20 }, { name: "Fresh tomato salsa", kcal: 25 },
        { name: "Corn salsa", kcal: 80 }, { name: "Green chili salsa", kcal: 15 },
        { name: "Red chili salsa", kcal: 30 }, { name: "Cheese", kcal: 110 },
        { name: "Sour cream", kcal: 110 }, { name: "Guacamole", kcal: 230 },
        { name: "Queso blanco", kcal: 120 }, { name: "Lettuce", kcal: 5 },
      ]},
      { name: "Sides", items: [
        { name: "Chips", kcal: 540 }, { name: "Side of guac", kcal: 230 },
        { name: "Side of queso", kcal: 120 },
      ]},
    ],
  },
  "Subway": {
    formats: [
      { name: "6-inch", kcal: 0, mult: 1 },
      { name: "Footlong (doubles everything)", kcal: 0, mult: 2 },
    ],
    groups: [
      { name: "Bread", items: [
        { name: "Italian bread", kcal: 200 }, { name: "Wheat bread", kcal: 210 },
        { name: "Italian Herbs & Cheese", kcal: 240 }, { name: "Wrap", kcal: 290 },
        { name: "No bread (salad)", kcal: 0 },
      ]},
      { name: "Protein", items: [
        { name: "Turkey", kcal: 50 }, { name: "Ham", kcal: 60 },
        { name: "Roast beef", kcal: 80 }, { name: "Rotisserie chicken", kcal: 80 },
        { name: "Steak", kcal: 110 }, { name: "Tuna", kcal: 250 },
        { name: "Meatballs in marinara", kcal: 240 },
      ]},
      { name: "Cheese", items: [
        { name: "American cheese", kcal: 40 }, { name: "Provolone", kcal: 50 },
        { name: "Pepper jack", kcal: 50 },
      ]},
      { name: "Veggies", items: [
        { name: "Lettuce", kcal: 5 }, { name: "Tomatoes", kcal: 10 },
        { name: "Onions", kcal: 10 }, { name: "Green peppers", kcal: 5 },
        { name: "Cucumbers", kcal: 5 }, { name: "Pickles", kcal: 0 },
        { name: "Olives", kcal: 15 }, { name: "Spinach", kcal: 5 },
        { name: "Jalapeños", kcal: 5 }, { name: "Avocado", kcal: 60 },
      ]},
      { name: "Sauce", items: [
        { name: "Mayo", kcal: 100 }, { name: "Light mayo", kcal: 50 },
        { name: "Ranch", kcal: 110 }, { name: "Chipotle Southwest", kcal: 100 },
        { name: "Sweet onion", kcal: 40 }, { name: "Honey mustard", kcal: 30 },
        { name: "Yellow mustard", kcal: 10 }, { name: "Oil & vinegar", kcal: 45 },
      ]},
    ],
  },
  "McDonald's": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Burgers & Sandwiches", items: [
        { name: "Big Mac", kcal: 590 }, { name: "Quarter Pounder w/ Cheese", kcal: 520 },
        { name: "McDouble", kcal: 400 }, { name: "Cheeseburger", kcal: 300 },
        { name: "McChicken", kcal: 400 }, { name: "Filet-O-Fish", kcal: 390 },
        { name: "McCrispy", kcal: 470 }, { name: "6pc McNuggets", kcal: 250 },
        { name: "10pc McNuggets", kcal: 410 },
      ]},
      { name: "Sides", items: [
        { name: "Fries (small)", kcal: 230 }, { name: "Fries (medium)", kcal: 320 },
        { name: "Fries (large)", kcal: 480 }, { name: "Apple slices", kcal: 15 },
      ]},
      { name: "Drinks & Desserts", items: [
        { name: "Coke (medium)", kcal: 200 }, { name: "Sprite (medium)", kcal: 200 },
        { name: "Sweet tea (medium)", kcal: 100 }, { name: "McFlurry Oreo", kcal: 510 },
        { name: "Chocolate shake (medium)", kcal: 620 }, { name: "Apple pie", kcal: 230 },
      ]},
      { name: "Breakfast", items: [
        { name: "Egg McMuffin", kcal: 310 }, { name: "Sausage McMuffin w/ Egg", kcal: 480 },
        { name: "Hash browns", kcal: 140 }, { name: "Hotcakes", kcal: 580 },
        { name: "Sausage burrito", kcal: 300 },
      ]},
    ],
  },
  "Taco Bell": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Tacos & Burritos", items: [
        { name: "Crunchy taco", kcal: 170 }, { name: "Soft taco", kcal: 180 },
        { name: "Doritos Locos taco", kcal: 170 }, { name: "Bean burrito", kcal: 350 },
        { name: "Burrito Supreme", kcal: 390 }, { name: "5-Layer burrito", kcal: 490 },
        { name: "Crunchwrap Supreme", kcal: 530 }, { name: "Chicken quesadilla", kcal: 510 },
        { name: "Mexican Pizza", kcal: 540 },
      ]},
      { name: "Sides & Extras", items: [
        { name: "Nachos BellGrande", kcal: 740 }, { name: "Chips & nacho cheese", kcal: 320 },
        { name: "Cinnamon twists", kcal: 170 }, { name: "Black beans & rice", kcal: 170 },
        { name: "Sour cream (add)", kcal: 30 }, { name: "Guacamole (add)", kcal: 35 },
      ]},
      { name: "Drinks", items: [
        { name: "Baja Blast (medium)", kcal: 220 }, { name: "Regular soda (medium)", kcal: 200 },
      ]},
    ],
  },
  "Wendy's": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Burgers & Sandwiches", items: [
        { name: "Dave's Single", kcal: 590 }, { name: "Dave's Double", kcal: 810 },
        { name: "Baconator", kcal: 950 }, { name: "Jr. Cheeseburger", kcal: 290 },
        { name: "Spicy Chicken Sandwich", kcal: 490 }, { name: "10pc Nuggets", kcal: 450 },
      ]},
      { name: "Sides", items: [
        { name: "Fries (medium)", kcal: 350 }, { name: "Chili (small)", kcal: 240 },
        { name: "Baked potato", kcal: 270 },
      ]},
      { name: "Drinks & Desserts", items: [
        { name: "Frosty (medium)", kcal: 510 }, { name: "Lemonade (medium)", kcal: 190 },
        { name: "Soda (medium)", kcal: 200 },
      ]},
    ],
  },
  "Chick-fil-A": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Entrees", items: [
        { name: "Chicken Sandwich", kcal: 440 }, { name: "Deluxe Sandwich", kcal: 500 },
        { name: "Spicy Chicken Sandwich", kcal: 450 }, { name: "8pc Nuggets", kcal: 250 },
        { name: "12pc Nuggets", kcal: 380 }, { name: "Grilled Sandwich", kcal: 390 },
        { name: "Cool Wrap", kcal: 660 },
      ]},
      { name: "Sides", items: [
        { name: "Waffle fries (medium)", kcal: 420 }, { name: "Mac & cheese (medium)", kcal: 450 },
        { name: "Fruit cup", kcal: 60 }, { name: "Side salad", kcal: 160 },
      ]},
      { name: "Drinks & Sauces", items: [
        { name: "Lemonade (medium)", kcal: 220 }, { name: "Sweet tea (medium)", kcal: 120 },
        { name: "Milkshake", kcal: 580 }, { name: "Chick-fil-A sauce", kcal: 140 },
        { name: "Polynesian sauce", kcal: 110 },
      ]},
    ],
  },
  "Panda Express": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Entrees", items: [
        { name: "Orange Chicken", kcal: 490 }, { name: "Beijing Beef", kcal: 480 },
        { name: "Broccoli Beef", kcal: 150 }, { name: "Kung Pao Chicken", kcal: 290 },
        { name: "Grilled Teriyaki Chicken", kcal: 340 }, { name: "Honey Walnut Shrimp", kcal: 430 },
        { name: "Mushroom Chicken", kcal: 220 },
      ]},
      { name: "Sides", items: [
        { name: "Chow Mein", kcal: 510 }, { name: "Fried Rice", kcal: 520 },
        { name: "White Rice", kcal: 380 }, { name: "Super Greens", kcal: 90 },
      ]},
      { name: "Extras", items: [
        { name: "Cream Cheese Rangoons (3)", kcal: 190 }, { name: "Chicken Egg Roll", kcal: 200 },
        { name: "Veggie Spring Roll (2)", kcal: 240 }, { name: "Fortune cookie", kcal: 30 },
      ]},
    ],
  },
  "Five Guys": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Burgers & Dogs", items: [
        { name: "Little Hamburger", kcal: 540 }, { name: "Little Cheeseburger", kcal: 630 },
        { name: "Hamburger (2 patties)", kcal: 700 }, { name: "Cheeseburger (2 patties)", kcal: 840 },
        { name: "Bacon Cheeseburger", kcal: 920 }, { name: "Hot Dog", kcal: 540 },
      ]},
      { name: "Toppings", items: [
        { name: "Mayo", kcal: 100 }, { name: "Ketchup", kcal: 15 },
        { name: "Mustard", kcal: 0 }, { name: "Grilled onions", kcal: 10 },
        { name: "Grilled mushrooms", kcal: 10 }, { name: "Lettuce/tomato/pickles", kcal: 15 },
        { name: "BBQ sauce", kcal: 50 }, { name: "A.1. sauce", kcal: 15 },
      ]},
      { name: "Fries & Shakes", items: [
        { name: "Fries (little)", kcal: 530 }, { name: "Fries (regular)", kcal: 950 },
        { name: "Milkshake", kcal: 670 },
      ]},
    ],
  },
  "Wingstop": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Wings", items: [
        { name: "6 classic wings", kcal: 430 }, { name: "8 classic wings", kcal: 570 },
        { name: "10 classic wings", kcal: 710 }, { name: "6 boneless wings", kcal: 570 },
        { name: "8 boneless wings", kcal: 760 }, { name: "3 crispy tenders", kcal: 530 },
      ]},
      { name: "Sides & Dips", items: [
        { name: "Seasoned fries (regular)", kcal: 430 }, { name: "Cheese fries", kcal: 670 },
        { name: "Ranch dip", kcal: 310 }, { name: "Blue cheese dip", kcal: 320 },
        { name: "Honey mustard", kcal: 190 }, { name: "Rolls (1)", kcal: 160 },
      ]},
    ],
  },
  "Starbucks": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Drinks (grande)", items: [
        { name: "Caffè latte", kcal: 190 }, { name: "Caramel macchiato", kcal: 250 },
        { name: "Caramel frappuccino", kcal: 380 }, { name: "Cold brew (black)", kcal: 5 },
        { name: "Pink Drink", kcal: 140 }, { name: "Chai tea latte", kcal: 240 },
        { name: "Hot chocolate", kcal: 370 }, { name: "Refresher", kcal: 90 },
      ]},
      { name: "Food", items: [
        { name: "Butter croissant", kcal: 260 }, { name: "Banana bread", kcal: 420 },
        { name: "Bacon & gouda sandwich", kcal: 360 }, { name: "Egg white bites", kcal: 170 },
        { name: "Cake pop", kcal: 140 }, { name: "Blueberry muffin", kcal: 360 },
      ]},
    ],
  },
  "Pizza place": {
    formats: [{ name: "Order", kcal: 0, mult: 1 }],
    groups: [
      { name: "Pizza (large slice)", items: [
        { name: "Cheese slice", kcal: 285 }, { name: "Pepperoni slice", kcal: 310 },
        { name: "Supreme slice", kcal: 330 }, { name: "Meat lover's slice", kcal: 380 },
        { name: "Veggie slice", kcal: 260 }, { name: "Extra slice (add another)", kcal: 300 },
      ]},
      { name: "Sides", items: [
        { name: "Garlic knots (2)", kcal: 180 }, { name: "Breadsticks (1)", kcal: 140 },
        { name: "6 wings", kcal: 540 }, { name: "Ranch dip", kcal: 130 },
        { name: "Caesar side salad", kcal: 220 },
      ]},
    ],
  },
};
